-- 1. FRED 전용 일 단위 지표 테이블(indicator_fred_daily_logs)
create table IF NOT EXISTS public.indicator_fred_daily_logs (
  id bigint generated by default as identity not null,
  category text null default 'Macro/Energy'::text,
  fred_wti double precision null,
  fred_brent double precision null,
  fred_usd_index double precision null,
  fred_treasury_10y double precision null,
  fred_treasury_2y double precision null,
  fred_natural_gas double precision null,
  fred_heating_oil double precision null,
  unit text null default 'index/usd/percent'::text,
  reference_date text not null,
  collected_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  constraint indicator_fred_daily_logs_pkey primary key (id),
  constraint indicator_fred_daily_date_unique unique (reference_date)
) TABLESPACE pg_default;

-- 기존 테이블에 대한 칼럼 추가 안전 구문
ALTER TABLE public.indicator_fred_daily_logs ADD COLUMN IF NOT EXISTS fred_treasury_2y double precision null;
ALTER TABLE public.indicator_fred_daily_logs ADD COLUMN IF NOT EXISTS fred_natural_gas double precision null;
ALTER TABLE public.indicator_fred_daily_logs ADD COLUMN IF NOT EXISTS fred_heating_oil double precision null;

-- 2. 새로운 월 단위 지표 테이블(indicator_fred_monthly_logs)
create table IF NOT EXISTS public.indicator_fred_monthly_logs (
  id bigint generated by default as identity not null,
  category text null default 'Macro/Supply Chain'::text,
  fred_gepu double precision null,
  fred_cpi double precision null,
  fred_pce double precision null,
  fred_unrate double precision null,
  fred_gdp double precision null,
  fred_indpro double precision null,
  fred_fedfunds double precision null,
  fred_csushpisa double precision null,
  fred_pcedg double precision null,
  fred_wheat double precision null,
  fred_corn double precision null,
  fred_soybean double precision null,
  fred_ppi double precision null,
  fred_bdi double precision null,
  unit text null default 'index/percent/usd'::text,
  reference_month text not null, 
  collected_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  constraint indicator_fred_monthly_logs_pkey primary key (id),
  constraint indicator_fred_monthly_month_unique unique (reference_month)
) TABLESPACE pg_default;

-- 기존 테이블에 대한 칼럼 추가 안전 구문
ALTER TABLE public.indicator_fred_monthly_logs ADD COLUMN IF NOT EXISTS fred_cpi double precision null;
ALTER TABLE public.indicator_fred_monthly_logs ADD COLUMN IF NOT EXISTS fred_pce double precision null;
ALTER TABLE public.indicator_fred_monthly_logs ADD COLUMN IF NOT EXISTS fred_unrate double precision null;
ALTER TABLE public.indicator_fred_monthly_logs ADD COLUMN IF NOT EXISTS fred_gdp double precision null;
ALTER TABLE public.indicator_fred_monthly_logs ADD COLUMN IF NOT EXISTS fred_indpro double precision null;
ALTER TABLE public.indicator_fred_monthly_logs ADD COLUMN IF NOT EXISTS fred_fedfunds double precision null;
ALTER TABLE public.indicator_fred_monthly_logs ADD COLUMN IF NOT EXISTS fred_csushpisa double precision null;
ALTER TABLE public.indicator_fred_monthly_logs ADD COLUMN IF NOT EXISTS fred_pcedg double precision null;
ALTER TABLE public.indicator_fred_monthly_logs ADD COLUMN IF NOT EXISTS fred_wheat double precision null;
ALTER TABLE public.indicator_fred_monthly_logs ADD COLUMN IF NOT EXISTS fred_corn double precision null;
ALTER TABLE public.indicator_fred_monthly_logs ADD COLUMN IF NOT EXISTS fred_soybean double precision null;
ALTER TABLE public.indicator_fred_monthly_logs ADD COLUMN IF NOT EXISTS fred_ppi double precision null;
ALTER TABLE public.indicator_fred_monthly_logs ADD COLUMN IF NOT EXISTS fred_bdi double precision null;
