-- 추론 엔진(Reasoning Engine)이 뱉어낸 JSON 데이터를 영구 저장하는 테이블
CREATE TABLE IF NOT EXISTS public.causal_chains (
  id bigint generated by default as identity not null,
  category text not null,               -- 예: Energy, Food, Utilities, Logistics
  tags text[] null,                     -- 예: ['Middle East', 'Energy']
  title text not null,                  -- 인과관계 제목
  description text not null,            -- 인과관계 내용 (원인 -> 파장 -> 결과)
  raw_shock_percent integer null,       -- 원자재 타격 예상률 (+)
  wallet_hit_percent integer null,      -- 내 지갑 타격 예상률 (+)
  transmission_time_months integer null,-- 전이 시차 (개월)
  source_news_url text null,            -- 어느 뉴스에서 추출했는지 파악하기 위한 원본 URL
  created_at timestamp with time zone null default now(),
  constraint causal_chains_pkey primary key (id)
) TABLESPACE pg_default;

-- 빠른 조회를 위한 카테고리별 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_causal_chains_category ON public.causal_chains USING btree (category);
